name: Master
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: latest
      - run: npm install
      - run: node src/index.js
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
