name: Master
on:
  schedule:
    - cron: "0 1 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm install
      - run: node src/operations/daily.js
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BACKUP_YOUTUBE_API_KEY: ${{ secrets.BACKUP_YOUTUBE_API_KEY }}
